language: php

php:
  - 5.3
  - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=1
    - CRAWLER_VERSION='2.3.*'
	
before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 
  - bash bin/selenium.sh
  - sh -c 'if [ "$CRAWLER_VERSION" != "" ]; then composer require --no-update symfony/dom-crawler=$CRAWLER_VERSION; fi;'
  - composer install --dev --prefer-source
script: phpunit
