language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.3
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh quantimodonew quantimodonew 'rvZ78B3M5ZUA4xfZ' localhost $WP_VERSION 

script: phpunit
